// Associates both accounts generated by generate-accounts.mjs with testnet
// USDC (0.0.429274) — required before either can send or receive it
// (TOKEN_NOT_ASSOCIATED_TO_ACCOUNT otherwise). Reused for Phase 4 Section B
// (docs/adr/0007): the same two Gate 0.4 accounts double as the relay
// operator (payee) and a paying node (payer) there, to avoid minting yet
// another pair of accounts and running the HBAR faucet dance again.
//
// Snippet adapted directly from @x402/hedera's own README ("Token Association").
import 'dotenv/config'
import { AccountId, Client, PrivateKey, TokenAssociateTransaction, TokenId } from '@x402/hedera'

const USDC_TESTNET = '0.0.429274'

async function associate(accountId, privateKeyHex, label) {
  const client = Client.forTestnet().setOperator(
    AccountId.fromString(accountId),
    PrivateKey.fromStringECDSA(privateKeyHex)
  )
  try {
    const response = await new TokenAssociateTransaction()
      .setAccountId(AccountId.fromString(accountId))
      .setTokenIds([TokenId.fromString(USDC_TESTNET)])
      .execute(client)
    const receipt = await response.getReceipt(client)
    console.log(`${label} (${accountId}): associated with USDC — status ${receipt.status.toString()}`)
  } catch (err) {
    if (String(err).includes('TOKEN_ALREADY_ASSOCIATED_TO_ACCOUNT')) {
      console.log(`${label} (${accountId}): already associated with USDC`)
    } else {
      throw err
    }
  } finally {
    client.close()
  }
}

await associate(process.env.HEDERA_CLIENT_ACCOUNT_ID, process.env.HEDERA_CLIENT_PRIVATE_KEY, 'Client (payer)')
await associate(
  process.env.HEDERA_SERVER_ACCOUNT_ID,
  process.env.HEDERA_SERVER_PRIVATE_KEY,
  'Server/relay-operator (payee)'
)

console.log(
  '\nNext: fund the payer account with testnet USDC at https://faucet.circle.com/ (pick "Hedera Testnet", paste the account id, solve the captcha).'
)
