package gateway

import (
	"encoding/hex"
	"strings"
	"testing"

	"golang.org/x/crypto/curve25519"
)

// Cross-language parity vectors, generated by actually running
// admincli/src/roles.ts's aclDigestECDH with these exact inputs (see the
// implementation commit — not hand-derived, not assumed). If this test ever
// fails after touching ACLDigestECDH, the Go and TS implementations have
// diverged and a granter/gateway pair running different halves of the stack
// would silently fail to agree on a digest.
var (
	vectorPriv = strings.Repeat("11", 32)
	vectorPub  = "0faa684ed28867b97f4a6a2dee5df8ce974e76b7018e3f22a1c4cf2678570f20"
)

func publicFromPrivate(privateKeyHex string) (string, error) {
	priv, err := decodeKey32(privateKeyHex)
	if err != nil {
		return "", err
	}
	pub, err := curve25519.X25519(priv, curve25519.Basepoint)
	if err != nil {
		return "", err
	}
	return hex.EncodeToString(pub), nil
}

func TestACLDigestECDH_MatchesTypeScriptReferenceImplementation(t *testing.T) {
	cases := []struct {
		service string
		want    string
	}{
		{"db", "a001f886b8a082696bf80b7eac0a4660129837021ef4587d15bebd48c795521c"},
		{"cache", "8a2605b6326d4b97059ca0336d8944ca8b45ce4f03044e3cc85f8caa5100cb51"},
	}

	for _, tc := range cases {
		got, err := ACLDigestECDH(vectorPriv, vectorPub, tc.service)
		if err != nil {
			t.Fatalf("service %q: %v", tc.service, err)
		}
		if got != tc.want {
			t.Errorf("service %q: got %s, want %s", tc.service, got, tc.want)
		}
	}
}

// TestACLDigestECDH_Symmetric proves the load-bearing claim from adr/0005:
// a granter and a gateway, computing with their own private key and the
// other's public key, derive the identical digest.
func TestACLDigestECDH_Symmetric(t *testing.T) {
	granterPriv := strings.Repeat("33", 32)
	gatewayPriv := strings.Repeat("44", 32)

	granterPub, err := publicFromPrivate(granterPriv)
	if err != nil {
		t.Fatal(err)
	}
	gatewayPub, err := publicFromPrivate(gatewayPriv)
	if err != nil {
		t.Fatal(err)
	}

	fromGranter, err := ACLDigestECDH(granterPriv, gatewayPub, "db")
	if err != nil {
		t.Fatal(err)
	}
	fromGateway, err := ACLDigestECDH(gatewayPriv, granterPub, "db")
	if err != nil {
		t.Fatal(err)
	}

	if fromGranter != fromGateway {
		t.Fatalf("ECDH symmetry broken: granter got %s, gateway got %s", fromGranter, fromGateway)
	}
}

func TestACLDigestECDH_CanonicalizesServiceName(t *testing.T) {
	got1, err := ACLDigestECDH(vectorPriv, vectorPub, "db")
	if err != nil {
		t.Fatal(err)
	}
	got2, err := ACLDigestECDH(vectorPriv, vectorPub, "  DB  ")
	if err != nil {
		t.Fatal(err)
	}
	if got1 != got2 {
		t.Fatalf("expected trim+lowercase canonicalization, got %s vs %s", got1, got2)
	}
}

func TestACLDigestECDH_RejectsBadKeyLength(t *testing.T) {
	if _, err := ACLDigestECDH("ab", vectorPub, "db"); err == nil {
		t.Fatal("expected error for short private key")
	}
	if _, err := ACLDigestECDH(vectorPriv, "ab", "db"); err == nil {
		t.Fatal("expected error for short public key")
	}
}
