// Package wgnode wraps wireguard-go's Device with the minimal surface
// brambled needs: create a node, add/remove peers by public key, read the
// current peer set back. Peer admission itself is not implemented here —
// WireGuard's own protocol already refuses a handshake from any public key
// that isn't in the device's peer table (see package admission, which is
// what decides who gets added).
//
// Real OS TUN is the default (Config.Netstack is false unless set) — the
// actual demo and the real Gate 0.2 cross-network run both need a genuine
// OS-visible interface, and defaulting to it means forgetting a flag can't
// silently produce the virtual path instead. netstack (gVisor virtual TUN,
// root-free) is an explicit opt-in, used only by automated tests and CI,
// which set Config.Netstack: true.
package wgnode

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"net"
	"net/netip"
	"os"
	"os/exec"
	"regexp"
	"runtime"
	"strconv"
	"strings"
	"time"

	"golang.org/x/crypto/curve25519"
	"golang.org/x/net/icmp"
	"golang.org/x/net/ipv4"
	"golang.zx2c4.com/wireguard/conn"
	"golang.zx2c4.com/wireguard/device"
	"golang.zx2c4.com/wireguard/tun"
	"golang.zx2c4.com/wireguard/tun/netstack"
)

// GenerateKeyPair produces a new WireGuard (Curve25519) key pair, hex-encoded.
// Real node identity eventually comes from enrollment (Ledger-backed private
// key storage, per docs/adr/0001) — this is for standing up a node ad hoc,
// e.g. in tests and the current minimal `brambled serve`.
func GenerateKeyPair() (privateHex, publicHex string, err error) {
	var priv [32]byte
	if _, err := rand.Read(priv[:]); err != nil {
		return "", "", fmt.Errorf("generating private key: %w", err)
	}
	// Curve25519 clamping, per RFC 7748 / WireGuard's own key generation.
	priv[0] &= 248
	priv[31] &= 127
	priv[31] |= 64

	var pub [32]byte
	curve25519.ScalarBaseMult(&pub, &priv)

	return hex.EncodeToString(priv[:]), hex.EncodeToString(pub[:]), nil
}

// PublicKeyFromPrivateHex derives the public key for an already-known
// hex-encoded private key (e.g. one supplied via -private-key rather than
// generated by GenerateKeyPair), so callers that need to advertise their own
// public key (see brambled/rendezvous) don't have to re-derive Curve25519
// math themselves.
func PublicKeyFromPrivateHex(privateHex string) (string, error) {
	raw, err := hex.DecodeString(privateHex)
	if err != nil {
		return "", fmt.Errorf("decoding private key: %w", err)
	}
	if len(raw) != 32 {
		return "", fmt.Errorf("private key must be 32 bytes, got %d", len(raw))
	}

	var priv, pub [32]byte
	copy(priv[:], raw)
	curve25519.ScalarBaseMult(&pub, &priv)

	return hex.EncodeToString(pub[:]), nil
}

type Node struct {
	dev  *device.Device
	tnet *netstack.Net
	cfg  Config
	// interfaceName is non-empty only for a real OS TUN node — used to add
	// and remove per-peer routes in AddPeer/RemovePeer. Empty in netstack
	// mode, where there's no OS route table to touch.
	interfaceName string
}

type Config struct {
	// PrivateKeyHex is the node's own WireGuard private key, hex-encoded.
	PrivateKeyHex string
	// ListenPort is the UDP port this node's outer transport binds to.
	ListenPort uint16
	// LocalAddress is this node's virtual address (netstack mode) or its
	// address on the real interface (derived from LocalPrefix if unset).
	LocalAddress netip.Addr
	// LocalPrefix is the subnet assigned to the real OS interface (e.g.
	// 10.77.0.1/24). Ignored in netstack mode.
	LocalPrefix netip.Prefix
	// InterfaceName overrides the auto-picked real interface name ("utun" on
	// darwin, letting the OS assign a free number; "bramble0" on linux).
	// Ignored in netstack mode.
	InterfaceName string
	// Netstack opts into the virtual (gVisor) TUN instead of a real OS
	// interface. Root-free, but not OS-visible — shell `ping`/`nc` cannot
	// reach it. Automated tests and CI set this; real usage should not.
	Netstack bool
}

func New(cfg Config) (*Node, error) {
	var dev *device.Device
	var tnet *netstack.Net
	var interfaceName string

	if cfg.Netstack {
		tunDev, n, err := netstack.CreateNetTUN([]netip.Addr{cfg.LocalAddress}, nil, device.DefaultMTU)
		if err != nil {
			return nil, fmt.Errorf("creating virtual TUN: %w", err)
		}
		tnet = n
		dev = device.NewDevice(tunDev, conn.NewDefaultBind(), device.NewLogger(device.LogLevelSilent, ""))
	} else {
		name := cfg.InterfaceName
		if name == "" {
			name = defaultInterfaceName()
		}
		tunDev, err := tun.CreateTUN(name, device.DefaultMTU)
		if err != nil {
			return nil, fmt.Errorf("creating OS TUN device %q: %w", name, err)
		}
		realName, nameErr := tunDev.Name()
		if nameErr != nil || realName == "" {
			realName = name
		}
		if err := configureInterface(realName, cfg.LocalPrefix); err != nil {
			tunDev.Close()
			return nil, fmt.Errorf("configuring interface %q: %w", realName, err)
		}
		interfaceName = realName
		dev = device.NewDevice(tunDev, conn.NewDefaultBind(), device.NewLogger(device.LogLevelSilent, ""))
	}

	conf := fmt.Sprintf("private_key=%s\nlisten_port=%d\n", cfg.PrivateKeyHex, cfg.ListenPort)
	if err := dev.IpcSet(conf); err != nil {
		dev.Close()
		return nil, fmt.Errorf("configuring device: %w", err)
	}

	if err := dev.Up(); err != nil {
		dev.Close()
		return nil, fmt.Errorf("bringing device up: %w", err)
	}

	return &Node{dev: dev, tnet: tnet, cfg: cfg, interfaceName: interfaceName}, nil
}

func defaultInterfaceName() string {
	if runtime.GOOS == "darwin" {
		return "utun"
	}
	return "bramble0"
}

// configureInterface assigns prefix's address to the real OS interface name,
// adds a route for the whole local subnet, and brings it up — the same two
// steps wg-quick's own macOS/Linux setup scripts perform (there is no
// wg-quick here, so this replicates them). A per-peer-route scheme was
// tried instead and reverted: it has no field evidence behind it, diverges
// from wg-quick's known-working convention, and a local same-machine
// rehearsal that seemed to motivate it can't validate this code path either
// way (see brambled/README.md's Gate 0.2 runbook — a real OS TUN node's
// addressing/routing is unverified until that two-machine run happens).
func configureInterface(name string, prefix netip.Prefix) error {
	if !prefix.IsValid() {
		return fmt.Errorf("LocalPrefix is required for a real OS TUN interface")
	}

	addr := prefix.Addr().String()
	switch runtime.GOOS {
	case "darwin":
		mask := net.IP(net.CIDRMask(prefix.Bits(), prefix.Addr().BitLen())).String()
		if err := runCmd("ifconfig", name, "inet", addr, addr, "netmask", mask, "up"); err != nil {
			return err
		}
		return runCmd("route", "add", "-net", prefix.Masked().String(), "-interface", name)
	case "linux":
		if err := runCmd("ip", "addr", "add", prefix.String(), "dev", name); err != nil {
			return err
		}
		return runCmd("ip", "link", "set", "dev", name, "up")
	default:
		return fmt.Errorf("real OS TUN configuration not implemented for GOOS=%s (use Config.Netstack)", runtime.GOOS)
	}
}

func runCmd(name string, args ...string) error {
	out, err := exec.Command(name, args...).CombinedOutput()
	if err != nil {
		return fmt.Errorf("%s %s: %w: %s", name, strings.Join(args, " "), err, strings.TrimSpace(string(out)))
	}
	return nil
}

// AddPeer authorizes publicKeyHex to complete a handshake with this node,
// routing allowedIP to it. endpoint is optional — omit it (zero value) for a
// peer that will dial in first; the device learns/updates the endpoint from
// the first valid handshake it receives (WireGuard's usual roaming
// behavior), which is why the admission loop doesn't need to know a peer's
// address to authorize it. On a real OS TUN node, routing for allowedIP
// comes from the whole-subnet route configureInterface already added — no
// per-peer route management here (see configureInterface's comment).
func (n *Node) AddPeer(publicKeyHex string, allowedIP netip.Prefix, endpoint *netip.AddrPort) error {
	var b strings.Builder
	fmt.Fprintf(&b, "public_key=%s\n", publicKeyHex)
	fmt.Fprintf(&b, "allowed_ip=%s\n", allowedIP.String())
	if endpoint != nil {
		fmt.Fprintf(&b, "endpoint=%s\n", endpoint.String())
	}
	return n.dev.IpcSet(b.String())
}

func (n *Node) RemovePeer(publicKeyHex string) error {
	conf := fmt.Sprintf("public_key=%s\nremove=true\n", publicKeyHex)
	return n.dev.IpcSet(conf)
}

// SetPersistentKeepalive makes this node send an unsolicited packet to
// publicKeyHex every seconds, even with nothing to transmit. Safe to call
// before or after AddPeer for the same key — UAPI "set" merges fields into
// a peer entry by public_key rather than replacing it.
//
// This exists for docs/adr/0008's data-plane relay: the relay learns each
// side's address purely from outbound UDP traffic it happens to observe,
// but WireGuard's own protocol never has the passive/responder side send
// anything until it's received the initiator's handshake first — normally
// fine, but fatal here, since the relay would never learn where to forward
// to. Persistent keepalive is what makes both sides proactively announce
// themselves to the relay regardless of who initiates the real handshake.
func (n *Node) SetPersistentKeepalive(publicKeyHex string, seconds int) error {
	conf := fmt.Sprintf("public_key=%s\npersistent_keepalive_interval=%d\n", publicKeyHex, seconds)
	return n.dev.IpcSet(conf)
}

// InterfaceName returns the real OS interface name this node configured
// (e.g. "utun7"), or "" in netstack mode. Exposed so callers can log it —
// e.g. so a runbook can say exactly which interface to inspect with
// `ifconfig`/`netstat -rn` (see brambled/README.md's Gate 0.2 runbook).
func (n *Node) InterfaceName() string {
	return n.interfaceName
}

type PeerInfo struct {
	PublicKeyHex        string
	AllowedIPs          []string
	LastHandshakeUnixNs int64
	// RxBytes is this peer's total received-byte counter, straight from
	// wireguard-go's UAPI `rx_bytes=` field (device/uapi.go, confirmed
	// directly against the vendored source, not assumed). Monotonic for
	// the life of the peer entry — used by docs/adr/0008's data-relay
	// failover watcher to detect a stalled relay (see
	// brambled/datarelay.WaitForStall): no per-packet WireGuard protocol
	// awareness needed, just "is this number still moving."
	RxBytes int64
}

// Handshaked reports whether this peer has ever completed a handshake.
func (p PeerInfo) Handshaked() bool { return p.LastHandshakeUnixNs > 0 }

var publicKeyLine = regexp.MustCompile(`^public_key=([0-9a-f]{64})$`)

// Peers parses the device's current peer table from the UAPI "get" output
// (see golang.zx2c4.com/wireguard/device.Device.IpcGet — the config protocol
// documented at https://www.wireguard.com/xplatform/#configuration-protocol).
func (n *Node) Peers() ([]PeerInfo, error) {
	raw, err := n.dev.IpcGet()
	if err != nil {
		return nil, err
	}

	var peers []PeerInfo
	var cur *PeerInfo
	for _, line := range strings.Split(raw, "\n") {
		if m := publicKeyLine.FindStringSubmatch(line); m != nil {
			peers = append(peers, PeerInfo{PublicKeyHex: m[1]})
			cur = &peers[len(peers)-1]
			continue
		}
		if cur == nil {
			continue
		}
		key, value, ok := strings.Cut(line, "=")
		if !ok {
			continue
		}
		switch key {
		case "allowed_ip":
			cur.AllowedIPs = append(cur.AllowedIPs, value)
		case "last_handshake_time_sec":
			secs, _ := strconv.ParseInt(value, 10, 64)
			cur.LastHandshakeUnixNs += secs * time.Second.Nanoseconds()
		case "last_handshake_time_nsec":
			nsecs, _ := strconv.ParseInt(value, 10, 64)
			cur.LastHandshakeUnixNs += nsecs
		case "rx_bytes":
			cur.RxBytes, _ = strconv.ParseInt(value, 10, 64)
		}
	}
	return peers, nil
}

// ListenTCP starts a TCP listener on this node's own tunnel address.
// Netstack-only, like Ping — real OS TUN connectivity is verified with the
// OS's own `nc`/tools (see the Gate 0.2 runbook in brambled/README.md).
func (n *Node) ListenTCP(port uint16) (net.Listener, error) {
	if n.tnet == nil {
		return nil, fmt.Errorf("ListenTCP requires a netstack node (Config.Netstack: true)")
	}
	return n.tnet.ListenTCP(&net.TCPAddr{IP: n.cfg.LocalAddress.AsSlice(), Port: int(port)})
}

// DialTCP connects to a peer's tunnel address over this node's tunnel.
// Netstack-only, like Ping.
func (n *Node) DialTCP(raddr netip.AddrPort) (net.Conn, error) {
	if n.tnet == nil {
		return nil, fmt.Errorf("DialTCP requires a netstack node (Config.Netstack: true)")
	}
	return n.tnet.DialTCP(&net.TCPAddr{IP: raddr.Addr().AsSlice(), Port: int(raddr.Port())})
}

// Ping sends an ICMP echo to raddr over this node's tunnel and reports
// whether a reply was received within timeout. Netstack-only — a real OS TUN
// node has no in-process socket to dial; verify it with the OS's own
// `ping`/`nc` instead (see the Gate 0.2 runbook in brambled/README.md).
func (n *Node) Ping(raddr netip.Addr, timeout time.Duration) (bool, error) {
	if n.tnet == nil {
		return false, fmt.Errorf("Ping requires a netstack node (Config.Netstack: true); real OS TUN nodes are verified with the OS's own ping/nc")
	}

	pc, err := n.tnet.DialPingAddr(n.cfg.LocalAddress, raddr)
	if err != nil {
		return false, err
	}
	defer pc.Close()

	if err := pc.SetDeadline(time.Now().Add(timeout)); err != nil {
		return false, err
	}

	echo := icmp.Message{
		Type: ipv4.ICMPTypeEcho,
		Code: 0,
		Body: &icmp.Echo{
			ID:   os.Getpid() & 0xffff,
			Seq:  1,
			Data: []byte("bramble-gate1.1"),
		},
	}
	wireBytes, err := echo.Marshal(nil)
	if err != nil {
		return false, fmt.Errorf("marshaling ICMP echo: %w", err)
	}
	if _, err := pc.Write(wireBytes); err != nil {
		return false, err
	}

	buf := make([]byte, 1500)
	_, err = pc.Read(buf)
	if err != nil {
		return false, nil // timeout or refusal — not an error, just "no reply"
	}
	return true, nil
}

func (n *Node) Close() {
	n.dev.Close()
}
